name: 功能请求 / Feature request
title: "[Feature] "
description: 提出你的功能请求 / Propose your feature request
labels: ["pending triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您花时间填写, 在提交问题之前, 请确保您完成以下操作
        1. Jump 默认不提供任何规则, 你可以查看 [Jump 官方文档](https://gkd.li) 后自行编写规则或者导入远程订阅, 请不要再提出类似想要XXX规则这种问题
        2. 请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
        3. 请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
        4. 请 **确保** 你想要的功能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上没有找到 (如果不是请先更新到最新版本验证后再提交问题)
        5. 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
        6. 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭
  - type: textarea
    id: feature-description
    attributes:
      label: |
        新功能描述
      description: |
        例如: 我希望在 Jump 中的什么页面添加什么功能, 以及这个功能的作用是什么\
        或者在规则定义中添加某个字段, 以及这个字段的作用是什么\
        请使用准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true
